# Generated by Django 3.2.25 on 2024-05-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
